name: micronsbinder
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.7.0
  - pip
  - pykdtree
  - itkwidgets
  - jupyterlab>=1.0
  - jupyter-dash
  - notebook==6.0.3
  - jupyter-server-proxy
  - dash
  - scipy
  - seaborn
  - imageio
  - nodejs
  - statsmodels
  - pip:
    - nglui
    - cloud-volume
    - annotationframeworkclient
    - meshparty
    - dashdataframe==0.4.1
    - gdown
    - networkx
    - tqdm
    - neuroglancer
